// ForexAI Services - Ready for Perplexity AI and FRED Integration
import { API_CONFIG, apiHelpers } from './apiConfig';

class ForexAIService {
  constructor() {
    this.perplexityApiKey = process.env.REACT_APP_PERPLEXITY_API_KEY;
    this.fredApiKey = process.env.REACT_APP_FRED_API_KEY;
    this.isInitialized = true;
    
    if (this.perplexityApiKey && this.perplexityApiKey !== 'placeholder_for_perplexity_key') {
      console.log('🤖 ForexAI Service initialized with Perplexity AI');
    }
  }

  // Check if service is ready
  isReady() {
    return this.perplexityApiKey && this.perplexityApiKey !== 'placeholder_for_perplexity_key';
  }

  // Check if FRED is ready
  isFredReady() {
    return this.fredApiKey && this.fredApiKey !== 'placeholder_for_fred_key';
  }

  // Generate Daily Market Recap using Perplexity AI + FRED Data
  async generateDailyRecap() {
    if (!this.isReady()) {
      console.log('⚠️ Perplexity API not ready, using mock data');
      return this.getMockDailyRecap();
    }

    try {
      console.log('🤖 Generating real-time daily market recap with economic data...');
      
      // Get latest economic data from FRED if available
      const economicData = await this.getLatestEconomicData();
      
      // Build enhanced prompt for professional report
      let prompt = `Tu es un analyste forex senior. Rédige un rapport quotidien professionnel sur le marché forex pour le ${new Date().toLocaleDateString('fr-FR')}.`;
      
      if (Object.keys(economicData).length > 0) {
        prompt += `\n\nDonnées économiques récentes FRED:`;
        Object.entries(economicData).forEach(([indicator, data]) => {
          prompt += `\n- ${indicator}: ${data.value} (${data.date})`;
        });
        prompt += `\n\nIntègre ces données officielles dans ton analyse.`;
      }
      
      prompt += `

STRUCTURE REQUISE:

**RÉSUMÉ EXÉCUTIF:**
[2-3 phrases sur la situation générale des marchés forex aujourd'hui]

**POINTS CLÉS DU JOUR:**

1. **[Titre impact positif]**
   Description claire de l'événement et son impact sur les devises.

2. **[Titre impact négatif]** 
   Description claire de l'événement et son impact sur les devises.

3. **[Titre impact neutre/important]**
   Description claire de l'événement et son impact sur les devises.

**SENTIMENT GLOBAL:** [Optimiste/Pessimiste/Neutre modéré]

**TENDANCE PRINCIPALE:** [Description en 1 phrase]

**RECOMMANDATIONS:**
- [Conseil 1 pour traders]
- [Conseil 2 pour traders]

Concentre-toi sur: EUR/USD, GBP/USD, USD/JPY, USD/CHF, AUD/USD, USD/CAD.
Écris un français professionnel mais accessible à un lycéen.
Maximum 300 mots total.`;
      
      const aiResponse = await this.callPerplexityAI(prompt);
      console.log('✅ Daily recap generated by AI with FRED data');
      
      // Parse the structured response
      const parsedReport = this.parseAIReport(aiResponse);
      
      return {
        date: new Date().toLocaleDateString('fr-FR'),
        summary: parsedReport.summary,
        keyPoints: parsedReport.keyPoints,
        aiInsights: {
          sentiment: parsedReport.sentiment,
          confidence: 88,
          mainTrend: parsedReport.mainTrend,
          recommendation: parsedReport.recommendations
        },
        economicData: economicData,
        timestamp: new Date().toISOString(),
        source: 'Perplexity AI + FRED Data',
        rawReport: aiResponse
      };
      
    } catch (error) {
      console.error('❌ Error generating daily recap:', error);
      const mockData = this.getMockDailyRecap();
      mockData.summary = "Erreur lors de la génération de l'analyse IA. Données de démonstration affichées.";
      return mockData;
    }
  }

  // Generate Currency Analysis using AI + Economic Data
  async generateCurrencyAnalysis(currency) {
    if (!this.isReady()) {
      console.log('⚠️ Perplexity API not ready, using mock data for', currency);
      return this.getMockCurrencyAnalysis(currency);
    }

    try {
      console.log(`🤖 Generating real-time analysis for ${currency}...`);
      
      const prompt = `Tu es un analyste forex expert. Analyse la devise ${currency} aujourd'hui de manière professionnelle et accessible.

STRUCTURE REQUISE:

**Score Fondamental:** [nombre entre 1-100]
**Score Technique:** [nombre entre 1-100]  
**Sentiment:** [Description courte du sentiment actuel]

**Facteurs Clés:**
• [Facteur économique 1]
• [Facteur économique 2] 
• [Facteur économique 3]
• [Facteur politique/monetary 4]

**Prévision:**
[Paragraphe de 2-3 phrases expliquant les perspectives à court/moyen terme pour cette devise, en français simple mais professionnel]

**Recommandation:** [ACHAT/VENTE/NEUTRE]
**Confiance:** [nombre entre 1-100]%

Sois précis, factuel, et accessible à un lycéen. Maximum 150 mots.`;
      
      const aiResponse = await this.callPerplexityAI(prompt);
      console.log(`✅ Currency analysis generated for ${currency}`);
      
      // Parse the structured response
      const parsedAnalysis = this.parseCurrencyAnalysis(aiResponse);
      
      return {
        ...parsedAnalysis,
        timestamp: new Date().toISOString(),
        source: 'Perplexity AI',
        rawAnalysis: aiResponse
      };
      
    } catch (error) {
      console.error(`❌ Error analyzing ${currency}:`, error);
      const mockData = this.getMockCurrencyAnalysis(currency);
      mockData.forecast = "Erreur lors de l'analyse IA. Données de démonstration affichées.";
      return mockData;
    }
  }

  // Deep Research using Perplexity AI
  async conductDeepResearch(topic) {
    if (!this.isReady()) {
      return this.getMockResearchData(topic);
    }

    try {
      const prompt = API_CONFIG.PROMPTS.DEEP_RESEARCH(topic);
      const research = await this.callPerplexityAI(prompt);
      return this.formatResearchResults(research);
    } catch (error) {
      console.error('Error conducting deep research:', error);
      return this.getMockResearchData(topic);
    }
  }

  // Private Methods

  async callPerplexityAI(prompt) {
    console.log('🤖 Calling Perplexity AI with prompt:', prompt.substring(0, 100) + '...');
    
    try {
      const response = await fetch('https://api.perplexity.ai/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.perplexityApiKey}`,
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify({
          model: 'llama-3.1-sonar-small-128k-online',
          messages: [
            {
              role: 'system',
              content: 'Tu es un analyste forex professionnel expert en analyse fondamentale. Fournis des analyses précises et actionnables en français pour les traders forex. Sois concis mais complet.'
            },
            {
              role: 'user', 
              content: prompt
            }
          ],
          max_tokens: 1500,
          temperature: 0.2,
          top_p: 0.9,
          stream: false
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('❌ Perplexity API Error:', response.status, errorText);
        throw new Error(`Perplexity API error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      console.log('✅ Perplexity AI Response received');
      return data.choices[0].message.content;
      
    } catch (error) {
      console.error('❌ Error calling Perplexity AI:', error);
      throw error;
    }
  }

  async getFredData(indicator, startDate = null, endDate = null) {
    if (!this.isFredReady()) {
      console.log('⚠️ FRED API not available, skipping economic data');
      return null;
    }

    try {
      console.log(`📊 Fetching FRED data for ${indicator}...`);
      
      const url = new URL('https://api.stlouisfed.org/fred/series/observations');
      url.searchParams.append('series_id', indicator);
      url.searchParams.append('api_key', this.fredApiKey);
      url.searchParams.append('file_type', 'json');
      url.searchParams.append('limit', '5'); // Get last 5 data points
      url.searchParams.append('sort_order', 'desc'); // Most recent first
      
      if (startDate) url.searchParams.append('observation_start', startDate);
      if (endDate) url.searchParams.append('observation_end', endDate);

      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`FRED API error: ${response.status}`);
      }

      const data = await response.json();
      console.log(`✅ FRED data received for ${indicator}`);
      return data;
      
    } catch (error) {
      console.error(`❌ Error fetching FRED data for ${indicator}:`, error);
      return null;
    }
  }

  async getLatestEconomicData() {
    if (!this.isFredReady()) {
      console.log('⚠️ FRED API not ready, skipping economic data');
      return {};
    }

    console.log('📊 Fetching latest economic indicators from FRED...');
    
    const indicators = [
      'FEDFUNDS',      // US Federal Funds Rate
      'CPIAUCSL',      // US CPI
      'UNRATE',        // US Unemployment Rate
      'GDPC1',         // US Real GDP
      'DEXUSEU',       // US/Euro Exchange Rate
      'DEXJPUS',       // Japan/US Exchange Rate
      'DEXUSUK'        // US/UK Exchange Rate
    ];

    const data = {};
    for (const indicator of indicators) {
      try {
        const result = await this.getFredData(indicator);
        if (result && result.observations && result.observations.length > 0) {
          // Get the most recent non-null value
          const validObs = result.observations.filter(obs => obs.value !== '.');
          if (validObs.length > 0) {
            data[indicator] = {
              value: validObs[0].value,
              date: validObs[0].date,
              series_id: indicator
            };
          }
        }
      } catch (error) {
        console.error(`❌ Error fetching ${indicator}:`, error);
      }
    }

    console.log('✅ Economic data fetched from FRED:', Object.keys(data));
    return data;
  }

  async getCurrencyIndicators(currency) {
    const indicatorMap = {
      'USD': ['FEDFUNDS', 'CPIAUCSL', 'UNRATE', 'GDP'],
      'EUR': ['ECBREFI', 'EA19CPHAINMEI'],
      'GBP': ['INTDSRUKM193N', 'GBRCPIALLMINMEI'],
      'JPY': ['JPNINTDSGDPM193N', 'JPNCPIALLMINMEI'],
      'CAD': ['INTDSRCAM193N', 'CANCPIALLMINMEI'],
      'AUD': ['INTDSRAUQ193N', 'AUSCPIALLQINMEI'],
      'CHF': ['INTDSRCHM193N'] // Swiss indicators
    };

    const indicators = indicatorMap[currency] || [];
    const data = {};

    for (const indicator of indicators) {
      try {
        data[indicator] = await this.getFredData(indicator);
      } catch (error) {
        console.error(`Error fetching ${indicator} for ${currency}:`, error);
      }
    }

    return data;
  }

  buildDailyRecapPrompt(economicData) {
    return `${API_CONFIG.PROMPTS.DAILY_RECAP}
    
Données économiques récentes:
${JSON.stringify(economicData, null, 2)}

Analyse ces données et fournis un récapitulatif quotidien complet du marché forex.`;
  }

  buildCurrencyAnalysisPrompt(currency, indicators) {
    return `${API_CONFIG.PROMPTS.CURRENCY_ANALYSIS(currency)}
    
Indicateurs économiques pour ${currency}:
${JSON.stringify(indicators, null, 2)}

Fournis une analyse fondamentale complète de cette devise.`;
  }

  // Mock Data Methods (used when APIs not available)
  getMockDailyRecap() {
    return {
      date: new Date().toLocaleDateString('fr-FR'),
      summary: "Les marchés forex montrent une volatilité accrue suite aux dernières déclarations de la BCE concernant l'inflation dans la zone euro. L'EUR/USD maintient une tendance haussière modérée.",
      keyPoints: [
        {
          title: "BCE maintient ses taux directeurs",
          impact: "positif",
          description: "La Banque Centrale Européenne a maintenu ses taux d'intérêt à 4.25%, conformément aux attentes du marché."
        },
        {
          title: "Dollar américain sous pression",
          impact: "négatif",
          description: "Le DXY recule de 0.3% face aux incertitudes sur la politique monétaire de la Fed."
        },
        {
          title: "Livre sterling en hausse",
          impact: "positif",
          description: "GBP/USD gagne 0.45% grâce aux données d'inflation britanniques favorables."
        }
      ],
      aiInsights: {
        sentiment: "Optimiste modéré",
        confidence: 78,
        mainTrend: "Affaiblissement du Dollar US face aux devises européennes",
        recommendation: "Surveiller les annonces Fed de mercredi pour confirmation de tendance"
      }
    };
  }

  getMockCurrencyAnalysis(currency) {
    const mockData = {
      EUR: {
        fundamentalScore: 78,
        technicalScore: 65,
        sentiment: "Haussier modéré",
        aiRating: "ACHAT",
        confidence: 76,
        forecast: "L'Euro devrait maintenir sa trajectoire haussière face au Dollar US, soutenu par une politique monétaire BCE équilibrée et des fondamentaux économiques solides."
      },
      USD: {
        fundamentalScore: 72,
        technicalScore: 58,
        sentiment: "Baissier léger",
        aiRating: "NEUTRE",
        confidence: 68,
        forecast: "Le Dollar US fait face à des vents contraires à court terme, mais reste soutenu par des fondamentaux économiques solides à long terme."
      },
      GBP: {
        fundamentalScore: 71,
        technicalScore: 73,
        sentiment: "Haussier",
        aiRating: "ACHAT",
        confidence: 73,
        forecast: "La Livre Sterling bénéficie d'une politique monétaire ferme de la BoE et d'une amélioration des relations commerciales post-Brexit."
      }
    };

    return mockData[currency] || mockData.USD;
  }

  getMockResearchData(topic) {
    return {
      topic,
      summary: `Recherche approfondie sur ${topic} et son impact sur les marchés forex.`,
      keyFindings: [
        "Impact historique significatif sur la volatilité des devises",
        "Corrélations fortes avec les politiques des banques centrales",
        "Implications pour les stratégies de trading à moyen terme"
      ],
      tradingRecommendations: [
        "Surveiller les niveaux de support/résistance clés",
        "Utiliser une gestion de risque stricte",
        "Considérer les hedges sur positions longues"
      ],
      confidence: 82
    };
  }

  formatDailyRecap(aiAnalysis, economicData) {
    // Format AI analysis into structured daily recap
    return {
      date: new Date().toLocaleDateString('fr-FR'),
      summary: aiAnalysis,
      economicData: economicData,
      timestamp: new Date().toISOString()
    };
  }

  formatCurrencyAnalysis(currency, aiAnalysis, indicators) {
    // Format AI analysis into structured currency analysis
    return {
      currency,
      analysis: aiAnalysis,
      indicators: indicators,
      timestamp: new Date().toISOString()
    };
  }

  formatResearchResults(research) {
    // Format research results
    return {
      research,
      timestamp: new Date().toISOString()
    };
  }
}

// Create singleton instance
const forexAIService = new ForexAIService();

export default forexAIService;