// ForexAI Services - Ready for Perplexity AI and FRED Integration
import { API_CONFIG, apiHelpers } from './apiConfig';

class ForexAIService {
  constructor() {
    this.perplexityApiKey = process.env.REACT_APP_PERPLEXITY_API_KEY;
    this.fredApiKey = process.env.REACT_APP_FRED_API_KEY;
    this.isInitialized = true;
    
    if (this.perplexityApiKey && this.perplexityApiKey !== 'placeholder_for_perplexity_key') {
      console.log('🤖 ForexAI Service initialized with Perplexity AI');
    }
  }

  // Check if service is ready
  isReady() {
    return this.perplexityApiKey && this.perplexityApiKey !== 'placeholder_for_perplexity_key';
  }

  // Check if FRED is ready
  isFredReady() {
    return this.fredApiKey && this.fredApiKey !== 'placeholder_for_fred_key';
  }

  // Generate Daily Market Recap using Perplexity AI
  async generateDailyRecap() {
    if (!this.isReady()) {
      console.log('⚠️ Perplexity API not ready, using mock data');
      return this.getMockDailyRecap();
    }

    try {
      console.log('🤖 Generating real-time daily market recap...');
      
      const prompt = `Analyse le marché forex d'aujourd'hui (${new Date().toLocaleDateString('fr-FR')}). 
      
      Fournis une analyse complète incluant:
      1. Résumé exécutif des mouvements de devises majeures
      2. 3 points clés du jour avec leur impact (positif/négatif)
      3. Sentiment global du marché
      4. Recommandations pour les traders
      
      Focus sur: EUR/USD, GBP/USD, USD/JPY, USD/CHF, AUD/USD, USD/CAD
      
      Réponds en JSON avec cette structure:
      {
        "summary": "résumé exécutif",
        "keyPoints": [
          {"title": "titre", "impact": "positif/négatif", "description": "description"},
          {"title": "titre", "impact": "positif/négatif", "description": "description"},
          {"title": "titre", "impact": "positif/négatif", "description": "description"}
        ],
        "sentiment": "sentiment global",
        "confidence": nombre_entre_0_100,
        "mainTrend": "tendance principale",
        "recommendation": "recommandation principale"
      }`;
      
      const aiResponse = await this.callPerplexityAI(prompt);
      console.log('✅ Daily recap generated by AI');
      
      // Try to parse JSON response
      try {
        const parsed = JSON.parse(aiResponse);
        return {
          date: new Date().toLocaleDateString('fr-FR'),
          summary: parsed.summary,
          keyPoints: parsed.keyPoints,
          aiInsights: {
            sentiment: parsed.sentiment,
            confidence: parsed.confidence,
            mainTrend: parsed.mainTrend,
            recommendation: parsed.recommendation
          },
          timestamp: new Date().toISOString(),
          source: 'Perplexity AI'
        };
      } catch (parseError) {
        console.log('⚠️ Could not parse JSON, using raw response');
        return {
          date: new Date().toLocaleDateString('fr-FR'),
          summary: aiResponse,
          keyPoints: this.getMockDailyRecap().keyPoints,
          aiInsights: {
            sentiment: "Analyse générée par IA",
            confidence: 85,
            mainTrend: "Basé sur analyse Perplexity AI",
            recommendation: "Voir analyse complète ci-dessus"
          },
          timestamp: new Date().toISOString(),
          source: 'Perplexity AI'
        };
      }
      
    } catch (error) {
      console.error('❌ Error generating daily recap:', error);
      const mockData = this.getMockDailyRecap();
      mockData.summary = "Erreur lors de la génération de l'analyse IA. Données de démonstration affichées.";
      return mockData;
    }
  }

  // Generate Currency Analysis using AI + Economic Data
  async generateCurrencyAnalysis(currency) {
    if (!this.isReady()) {
      console.log('⚠️ Perplexity API not ready, using mock data for', currency);
      return this.getMockCurrencyAnalysis(currency);
    }

    try {
      console.log(`🤖 Generating real-time analysis for ${currency}...`);
      
      const prompt = `Analyse fondamentale complète de la devise ${currency} aujourd'hui.
      
      Fournis une analyse détaillée incluant:
      1. Score fondamental (0-100)
      2. Score technique (0-100) 
      3. Sentiment actuel du marché
      4. Facteurs clés influençant la devise (4 points maximum)
      5. Prévision et recommandation (ACHAT/VENTE/NEUTRE)
      6. Niveau de confiance (0-100)
      
      Réponds en JSON avec cette structure exacte:
      {
        "fundamentalScore": nombre_0_100,
        "technicalScore": nombre_0_100,
        "sentiment": "sentiment_description",
        "keyFactors": ["facteur1", "facteur2", "facteur3", "facteur4"],
        "forecast": "prévision_détaillée",
        "aiRating": "ACHAT/VENTE/NEUTRE",
        "confidence": nombre_0_100
      }`;
      
      const aiResponse = await this.callPerplexityAI(prompt);
      console.log(`✅ Currency analysis generated for ${currency}`);
      
      try {
        const parsed = JSON.parse(aiResponse);
        return {
          ...parsed,
          timestamp: new Date().toISOString(),
          source: 'Perplexity AI'
        };
      } catch (parseError) {
        console.log('⚠️ Could not parse JSON for currency analysis');
        const mockData = this.getMockCurrencyAnalysis(currency);
        mockData.forecast = aiResponse;
        mockData.source = 'Perplexity AI';
        return mockData;
      }
      
    } catch (error) {
      console.error(`❌ Error analyzing ${currency}:`, error);
      const mockData = this.getMockCurrencyAnalysis(currency);
      mockData.forecast = "Erreur lors de l'analyse IA. Données de démonstration affichées.";
      return mockData;
    }
  }

  // Deep Research using Perplexity AI
  async conductDeepResearch(topic) {
    if (!this.isReady()) {
      return this.getMockResearchData(topic);
    }

    try {
      const prompt = API_CONFIG.PROMPTS.DEEP_RESEARCH(topic);
      const research = await this.callPerplexityAI(prompt);
      return this.formatResearchResults(research);
    } catch (error) {
      console.error('Error conducting deep research:', error);
      return this.getMockResearchData(topic);
    }
  }

  // Private Methods

  async callPerplexityAI(prompt) {
    console.log('🤖 Calling Perplexity AI with prompt:', prompt.substring(0, 100) + '...');
    
    try {
      const response = await fetch('https://api.perplexity.ai/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.perplexityApiKey}`,
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify({
          model: 'llama-3.1-sonar-small-128k-online',
          messages: [
            {
              role: 'system',
              content: 'Tu es un analyste forex professionnel expert en analyse fondamentale. Fournis des analyses précises et actionnables en français pour les traders forex. Sois concis mais complet.'
            },
            {
              role: 'user', 
              content: prompt
            }
          ],
          max_tokens: 1500,
          temperature: 0.2,
          top_p: 0.9,
          stream: false
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('❌ Perplexity API Error:', response.status, errorText);
        throw new Error(`Perplexity API error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      console.log('✅ Perplexity AI Response received');
      return data.choices[0].message.content;
      
    } catch (error) {
      console.error('❌ Error calling Perplexity AI:', error);
      throw error;
    }
  }

  async getFredData(indicator, startDate = null, endDate = null) {
    const url = new URL(API_CONFIG.FRED.BASE_URL + API_CONFIG.FRED.ENDPOINTS.SERIES);
    url.searchParams.append('series_id', indicator);
    url.searchParams.append('api_key', this.fredApiKey);
    url.searchParams.append('file_type', 'json');
    
    if (startDate) url.searchParams.append('observation_start', startDate);
    if (endDate) url.searchParams.append('observation_end', endDate);

    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`FRED API error: ${response.status}`);
    }

    return await response.json();
  }

  async getLatestEconomicData() {
    const indicators = [
      'FEDFUNDS', 'CPIAUCSL', 'UNRATE', // US data
      'ECBREFI', 'EA19CPHAINMEI', // EU data
      'JPNINTDSGDPM193N', 'GBRCPIALLMINMEI' // Japan, UK data
    ];

    const data = {};
    for (const indicator of indicators) {
      try {
        data[indicator] = await this.getFredData(indicator);
      } catch (error) {
        console.error(`Error fetching ${indicator}:`, error);
      }
    }

    return data;
  }

  async getCurrencyIndicators(currency) {
    const indicatorMap = {
      'USD': ['FEDFUNDS', 'CPIAUCSL', 'UNRATE', 'GDP'],
      'EUR': ['ECBREFI', 'EA19CPHAINMEI'],
      'GBP': ['INTDSRUKM193N', 'GBRCPIALLMINMEI'],
      'JPY': ['JPNINTDSGDPM193N', 'JPNCPIALLMINMEI'],
      'CAD': ['INTDSRCAM193N', 'CANCPIALLMINMEI'],
      'AUD': ['INTDSRAUQ193N', 'AUSCPIALLQINMEI'],
      'CHF': ['INTDSRCHM193N'] // Swiss indicators
    };

    const indicators = indicatorMap[currency] || [];
    const data = {};

    for (const indicator of indicators) {
      try {
        data[indicator] = await this.getFredData(indicator);
      } catch (error) {
        console.error(`Error fetching ${indicator} for ${currency}:`, error);
      }
    }

    return data;
  }

  buildDailyRecapPrompt(economicData) {
    return `${API_CONFIG.PROMPTS.DAILY_RECAP}
    
Données économiques récentes:
${JSON.stringify(economicData, null, 2)}

Analyse ces données et fournis un récapitulatif quotidien complet du marché forex.`;
  }

  buildCurrencyAnalysisPrompt(currency, indicators) {
    return `${API_CONFIG.PROMPTS.CURRENCY_ANALYSIS(currency)}
    
Indicateurs économiques pour ${currency}:
${JSON.stringify(indicators, null, 2)}

Fournis une analyse fondamentale complète de cette devise.`;
  }

  // Mock Data Methods (used when APIs not available)
  getMockDailyRecap() {
    return {
      date: new Date().toLocaleDateString('fr-FR'),
      summary: "Les marchés forex montrent une volatilité accrue suite aux dernières déclarations de la BCE concernant l'inflation dans la zone euro. L'EUR/USD maintient une tendance haussière modérée.",
      keyPoints: [
        {
          title: "BCE maintient ses taux directeurs",
          impact: "positif",
          description: "La Banque Centrale Européenne a maintenu ses taux d'intérêt à 4.25%, conformément aux attentes du marché."
        },
        {
          title: "Dollar américain sous pression",
          impact: "négatif",
          description: "Le DXY recule de 0.3% face aux incertitudes sur la politique monétaire de la Fed."
        },
        {
          title: "Livre sterling en hausse",
          impact: "positif",
          description: "GBP/USD gagne 0.45% grâce aux données d'inflation britanniques favorables."
        }
      ],
      aiInsights: {
        sentiment: "Optimiste modéré",
        confidence: 78,
        mainTrend: "Affaiblissement du Dollar US face aux devises européennes",
        recommendation: "Surveiller les annonces Fed de mercredi pour confirmation de tendance"
      }
    };
  }

  getMockCurrencyAnalysis(currency) {
    const mockData = {
      EUR: {
        fundamentalScore: 78,
        technicalScore: 65,
        sentiment: "Haussier modéré",
        aiRating: "ACHAT",
        confidence: 76,
        forecast: "L'Euro devrait maintenir sa trajectoire haussière face au Dollar US, soutenu par une politique monétaire BCE équilibrée et des fondamentaux économiques solides."
      },
      USD: {
        fundamentalScore: 72,
        technicalScore: 58,
        sentiment: "Baissier léger",
        aiRating: "NEUTRE",
        confidence: 68,
        forecast: "Le Dollar US fait face à des vents contraires à court terme, mais reste soutenu par des fondamentaux économiques solides à long terme."
      },
      GBP: {
        fundamentalScore: 71,
        technicalScore: 73,
        sentiment: "Haussier",
        aiRating: "ACHAT",
        confidence: 73,
        forecast: "La Livre Sterling bénéficie d'une politique monétaire ferme de la BoE et d'une amélioration des relations commerciales post-Brexit."
      }
    };

    return mockData[currency] || mockData.USD;
  }

  getMockResearchData(topic) {
    return {
      topic,
      summary: `Recherche approfondie sur ${topic} et son impact sur les marchés forex.`,
      keyFindings: [
        "Impact historique significatif sur la volatilité des devises",
        "Corrélations fortes avec les politiques des banques centrales",
        "Implications pour les stratégies de trading à moyen terme"
      ],
      tradingRecommendations: [
        "Surveiller les niveaux de support/résistance clés",
        "Utiliser une gestion de risque stricte",
        "Considérer les hedges sur positions longues"
      ],
      confidence: 82
    };
  }

  formatDailyRecap(aiAnalysis, economicData) {
    // Format AI analysis into structured daily recap
    return {
      date: new Date().toLocaleDateString('fr-FR'),
      summary: aiAnalysis,
      economicData: economicData,
      timestamp: new Date().toISOString()
    };
  }

  formatCurrencyAnalysis(currency, aiAnalysis, indicators) {
    // Format AI analysis into structured currency analysis
    return {
      currency,
      analysis: aiAnalysis,
      indicators: indicators,
      timestamp: new Date().toISOString()
    };
  }

  formatResearchResults(research) {
    // Format research results
    return {
      research,
      timestamp: new Date().toISOString()
    };
  }
}

// Create singleton instance
const forexAIService = new ForexAIService();

export default forexAIService;